#undef TAPPING_TERM
#define TAPPING_TERM 175

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 1217

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 4

#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 60

#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "VadWM/QzjqNW"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 1

#define RGB_MATRIX_STARTUP_SPD 60

